const codes = {
  'en': {
    'lower': {
      'Backquote': '`',
      'Digit1': '1',
      'Digit2': '2',
      'Digit3': '3',
      'Digit4': '4',
      'Digit5': '5',
      'Digit6': '6',
      'Digit7': '7',
      'Digit8': '8',
      'Digit9': '9',
      'Digit0': '0',
      'Minus': '-',
      'Equal': '=',
      'Backspace': '&larr;&nbsp;Backspace',

      'Tab': 'Tab',
      'KeyQ': 'q',
      'KeyW': 'w',
      'KeyE': 'e',
      'KeyR': 'r',
      'KeyT': 't',
      'KeyY': 'y',
      'KeyU': 'u',
      'KeyI': 'i',
      'KeyO': 'o',
      'KeyP': 'p',
      'BracketLeft': '[',
      'BracketRight': ']',
      'Backslash': '\\',
      'Delete': 'Delete',

      'CapsLock': 'Caps Lock',
      'KeyA': 'a',
      'KeyS': 's',
      'KeyD': 'd',
      'KeyF': 'f',
      'KeyG': 'g',
      'KeyH': 'h',
      'KeyJ': 'j',
      'KeyK': 'k',
      'KeyL': 'l',
      'Semicolon': ';',
      'Quote': '\'',
      'Enter': 'Enter',

      'ShiftLeft': 'Shift',
      'KeyZ': 'z',
      'KeyX': 'x',
      'KeyC': 'c',
      'KeyV': 'v',
      'KeyB': 'b',
      'KeyN': 'n',
      'KeyM': 'm',
      'Comma': ',',
      'Period': '.',
      'Slash': '/',
      'ArrowUp': '&uarr;',
      'ShiftRight': 'Shift',

      'ControlLeft': 'Ctrl',
      'MetaLeft': 'Win',
      'AltLeft': 'Alt',
      'Space': 'Space',
      'AltRight': 'Alt',
      'ControlRight': 'Ctrl',
      'ArrowLeft': '&larr;',
      'ArrowDown': '&darr;',
      'ArrowRight': '&rarr;'
    },

    'upper': {
      'Backquote': '~',
      'Digit1': '!',
      'Digit2': '@',
      'Digit3': '#',
      'Digit4': '$',
      'Digit5': '%',
      'Digit6': '^',
      'Digit7': '&',
      'Digit8': '*',
      'Digit9': '(',
      'Digit0': ')',
      'Minus': '_',
      'Equal': '+',
      'Backspace': '&larr;&nbsp;Backspace',

      'Tab': 'Tab',
      'KeyQ': 'Q',
      'KeyW': 'W',
      'KeyE': 'E',
      'KeyR': 'R',
      'KeyT': 'T',
      'KeyY': 'Y',
      'KeyU': 'U',
      'KeyI': 'I',
      'KeyO': 'O',
      'KeyP': 'P',
      'BracketLeft': '{',
      'BracketRight': '}',
      'Backslash': '\|',
      'Delete': 'Delete',

      'CapsLock': 'Caps Lock',
      'KeyA': 'A',
      'KeyS': 'S',
      'KeyD': 'D',
      'KeyF': 'F',
      'KeyG': 'G',
      'KeyH': 'H',
      'KeyJ': 'J',
      'KeyK': 'K',
      'KeyL': 'L',
      'Semicolon': ':',
      'Quote': '\"',
      'Enter': 'Enter',

      'ShiftLeft': 'Shift',
      'KeyZ': 'Z',
      'KeyX': 'X',
      'KeyC': 'C',
      'KeyV': 'V',
      'KeyB': 'B',
      'KeyN': 'N',
      'KeyM': 'M',
      'Comma': '<',
      'Period': '>',
      'Slash': '?',
      'ArrowUp': '&uarr;',
      'ShiftRight': 'Shift',

      'ControlLeft': 'Ctrl',
      'MetaLeft': 'Win',
      'AltLeft': 'Alt',
      'Space': 'Space',
      'AltRight': 'Alt',
      'ControlRight': 'Ctrl',
      'ArrowLeft': '&larr;',
      'ArrowDown': '&darr;',
      'ArrowRight': '&rarr;'
    }
  },

  'ru': {
    'lower': {
      'Backquote': 'ё',
      'Digit1': '1',
      'Digit2': '2',
      'Digit3': '3',
      'Digit4': '4',
      'Digit5': '5',
      'Digit6': '6',
      'Digit7': '7',
      'Digit8': '8',
      'Digit9': '9',
      'Digit0': '0',
      'Minus': '-',
      'Equal': '=',
      'Backspace': '&larr;&nbsp;Backspace',

      'Tab': 'Tab',
      'KeyQ': 'й',
      'KeyW': 'ц',
      'KeyE': 'у',
      'KeyR': 'к',
      'KeyT': 'е',
      'KeyY': 'н',
      'KeyU': 'г',
      'KeyI': 'ш',
      'KeyO': 'щ',
      'KeyP': 'з',
      'BracketLeft': 'х',
      'BracketRight': 'ъ',
      'Backslash': '\\',
      'Delete': 'Delete',

      'CapsLock': 'Caps Lock',
      'KeyA': 'ф',
      'KeyS': 'ы',
      'KeyD': 'в',
      'KeyF': 'а',
      'KeyG': 'п',
      'KeyH': 'р',
      'KeyJ': 'о',
      'KeyK': 'л',
      'KeyL': 'д',
      'Semicolon': 'ж',
      'Quote': 'э',
      'Enter': 'Enter',

      'ShiftLeft': 'Shift',
      'KeyZ': 'я',
      'KeyX': 'ч',
      'KeyC': 'с',
      'KeyV': 'м',
      'KeyB': 'и',
      'KeyN': 'т',
      'KeyM': 'ь',
      'Comma': 'б',
      'Period': 'ю',
      'Slash': '.',
      'ArrowUp': '&uarr;',
      'ShiftRight': 'Shift',

      'ControlLeft': 'Ctrl',
      'MetaLeft': 'Win',
      'AltLeft': 'Alt',
      'Space': 'Space',
      'AltRight': 'Alt',
      'ControlRight': 'Ctrl',
      'ArrowLeft': '&larr;',
      'ArrowDown': '&darr;',
      'ArrowRight': '&rarr;'
    },

    'upper': {
      'Backquote': 'Ё',
      'Digit1': '!',
      'Digit2': '"',
      'Digit3': '№',
      'Digit4': ';',
      'Digit5': '%',
      'Digit6': ':',
      'Digit7': '?',
      'Digit8': '*',
      'Digit9': '(',
      'Digit0': ')',
      'Minus': '_',
      'Equal': '+',
      'Backspace': '&larr;&nbsp;Backspace',

      'Tab': 'Tab',
      'KeyQ': 'Й',
      'KeyW': 'Ц',
      'KeyE': 'У',
      'KeyR': 'К',
      'KeyT': 'Е',
      'KeyY': 'Н',
      'KeyU': 'Г',
      'KeyI': 'Ш',
      'KeyO': 'Щ',
      'KeyP': 'З',
      'BracketLeft': 'Х',
      'BracketRight': 'Ъ',
      'Backslash': '/',
      'Delete': 'Delete',

      'CapsLock': 'Caps Lock',
      'KeyA': 'Ф',
      'KeyS': 'Ы',
      'KeyD': 'В',
      'KeyF': 'А',
      'KeyG': 'П',
      'KeyH': 'Р',
      'KeyJ': 'О',
      'KeyK': 'Л',
      'KeyL': 'Д',
      'Semicolon': 'Ж',
      'Quote': 'Э',
      'Enter': 'Enter',

      'ShiftLeft': 'Shift',
      'KeyZ': 'Я',
      'KeyX': 'Ч',
      'KeyC': 'С',
      'KeyV': 'М',
      'KeyB': 'И',
      'KeyN': 'Т',
      'KeyM': 'Ь',
      'Comma': 'Б',
      'Period': 'Ю',
      'Slash': ',',
      'ArrowUp': '&uarr;',
      'ShiftRight': 'Shift',

      'ControlLeft': 'Ctrl',
      'MetaLeft': 'Win',
      'AltLeft': 'Alt',
      'Space': 'Space',
      'AltRight': 'Alt',
      'ControlRight': 'Ctrl',
      'ArrowLeft': '&larr;',
      'ArrowDown': '&darr;',
      'ArrowRight': '&rarr;'
    }
  }
}

// module.exports = {codes}