const codes = {
  'en': {
    'lower': {
      'Backquote': '`',
      'Digit1': 1,
      'Digit2': 2,
      'Digit3': 3,
      'Digit4': 4,
      'Digit5': 5,
      'Digit6': 6,
      'Digit7': 7,
      'Digit8': 8,
      'Digit9': 9,
      'Digit0': 0,
      'Minus': '-',
      'Equal': '=',
      'Backspace': '<-- Back space',

      'Tab': 'Tab',
      'KeyQ': 'q',
      'KeyW': 'w',
      'KeyE': 'e',
      'KeyR': 'r',
      'KeyT': 't',
      'KeyY': 'y',
      'KeyU': 'u',
      'KeyI': 'i',
      'KeyO': 'o',
      'KeyP': 'p',
      'BracketLeft': '[',
      'BracketRight': ']',
      'Backslash': '\\',
      'Delete': 'Delete',

      'CapsLock': 'Caps Lock',
      'KeyA': 'a',
      'KeyS': 's',
      'KeyD': 'd',
      'KeyF': 'f',
      'KeyG': 'g',
      'KeyH': 'h',
      'KeyJ': 'j',
      'KeyK': 'k',
      'KeyL': 'l',
      'Semicolon': ';',
      'Quote': '\'',
      'Enter': 'Enter',

      'ShiftLeft': 'Shift',
      'KeyZ': 'z',
      'KeyX': 'x',
      'KeyC': 'c',
      'KeyV': 'v',
      'KeyB': 'b',
      'KeyN': 'n',
      'KeyM': 'm',
      'Comma': ',',
      'Period': '.',
      'Slash': '/',
      'ArrowUp': '^',
      'ShiftRight': 'Shift',

      'ControlLeft': 'Ctrl',
      'MetaLeft': 'Win',
      'AltLeft': 'Alt',
      'Space': 'Space',
      'AltRight': 'Alt',
      'ControlRight': 'Control',
      'ArrowLeft': '<==',
      'ArrowDown': 'v',
      'ArrowRight': '==>',
    },

    'upper': {
      'Backquote': '~',
      'Digit1': 1,
      'Digit2': 2,
      'Digit3': 3,
      'Digit4': 4,
      'Digit5': 5,
      'Digit6': 6,
      'Digit7': 7,
      'Digit8': 8,
      'Digit9': 9,
      'Digit0': 0,
      'Minus': '_',
      'Equal': '+',
      'Backspace': 'Backspace'
    }
  }
}

// module.exports = {codes}